name: 'Audit'
on:
  pull_request:
    paths:
      - "**/package.json"
      - "**/package-lock.json"
  push:
    paths:
      - "**/package.json"
      - "**/package-lock.json"

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                  npm install
            - run: |
                  npm audit
